## baseURL = 'https://example.org/'
## languageCode = 'en-us'
## title = 'My New Hugo Site'
## theme = 'not-much'

# The following line is needed
# when running the example site
# from a subdir of the theme
# themesDir = "themes/not-much"

title = "Rudrrayan Manna"
languageCode = "en-us"
baseURL = "https://www.ron0.dev/"
copyright = "from Ron0Studios"

[markup]
  [markup.highlight]
    style = 'infeinermium'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
theme = "auto"
palette = "infeinermium"
showThemeNotice = false
showPostsSummary = true

# Giscus Comment System
[params.giscus]
repository = "username/repository"
repositoryId = "repositoryId"
categoryName = "categoryName"
categoryId = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"
language = "en"
lazyLoading = true

# Navigation
[menu]
  [[menu.main]]
    identifier = "home"
    name = "home"
    title = "Home"
    url = "/"
    weight = 1
  
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/posts"
    weight = 3
  
#  [[menu.main]]
#    identifier = "about"
#    name = "about"
#    title = "About"
#    url = "/about"
#    weight = 2
  
#  [[menu.main]]
#    identifier = "tags"
#    name = "tags"
#    title = "tags"
#    url = "/tags"
#    weight = 4

  [[menu.main]]
    identifier = "github"
    name = "github"
    title = "GitHub"
    url = "https://github.com/ron0studios"
    weight = 5

  [[menu.main]]
    identifier = "linkedin"
    name = "linkedin"
    title = "LinkedIn"
    url = "https://www.linkedin.com/in/rudrrayan/"
    weight = 5
