baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Rudrrayan Manna'
theme = ["hugo-admonitions",'not-much']
copyright = "Rudrrayan Manna"

[params]
theme = "dark"
palette = "theme"
showThemeNotice = false
showPostsSummary = true

# Navigation
[menu]
  [[menu.main]]
    identifier = "home"
    name = "home"
    title = "Home"
    url = "/"
    weight = 1
  
  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "About"
    url = "/about"
    weight = 2

  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/posts"
    weight = 3
  
  
  [[menu.main]]
    identifier = "github"
    name = "github"
    title = "GitHub"
    url = "https://github.com/ron0studios"
    weight = 4

  [[menu.main]]
    identifier = "linkedin"
    name = "linkedin"
    title = "linkedin"
    url = "https://www.linkedin.com/in/rudrrayan/"
    weight = 5

  [[menu.main]]
    identifier = "notes"
    name = "notes"
    title = "Knowledge Base"
    url = "/notes"
    weight = 6



[caches]
  [caches.images]
    dir = ':cacheDir/images'
